server:
  port: 8080
  servlet:
    context-path: /pms
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/property_management_system?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 200
      minimum-idle: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy #开启驼峰命名
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #建表时指定使用innodb 引擎