server:
  port: 8089
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
  datasource:
    url: jdbc:mysql://localhost:3306/property_management_system?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 200
      minimum-idle: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy #开启驼峰命名
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #建表时指定使用innodb 引擎
#jwt:
#  expiration: 30 # 过期时间 单位分钟
#  time-out: 30   # 超时时间 单位分钟
#  secret: uKd?J|tt9wE[._U+$==X?-@#NZ\,Um=@
jwt:
  secret: com.itmk
  #30分钟过期
  expiration: 30
  time-out: 30
